name: 'Update Obmondo Kubernetes'
description: 'Create a PR in a GitOps repo with the newest release of Obmondo Kubernetes'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-pull-request'
  color: 'blue'
